### PR TITLE
tests: add dummy interface tests and imrpove interface_common tests

### LINKED ISSUE #4: Improve the CI test to use nispor systemd service and socket

### PR DESCRIPTION
**Pull request by ffmancera**

### CODE REVIEW

**Comment by cathay4t** [comment]
Can you explain why changing dummy to veth instead of adding veth test?

**Comment by ffmancera** [comment]
> Can you explain why changing dummy to veth instead of adding veth test?

It is needed because dummy interfaces do not support set the state as up with ip link.

**Review by cathay4t — APPROVED** [review]
Thanks. In that case, I will approve it.

**Comment by cathay4t** [comment]
@ffmancera Please rebase. Thank you.

**Comment by ffmancera** [comment]
Rebased, thanks!

**Comment by ffmancera** [comment]
Are we requiring to sign all the commits with the GPG key? Is that intentional? Thanks!

**Comment by cathay4t** [comment]
@ffmancera I only sign the tag. Signing commit is waste my time on typing my long(16+) password even with gpg-agent running.

**Comment by cathay4t** [comment]
@ffmancera Oops, I set the github setting wrong. Should be OK now. Merged.

**Pull request merged**
