### PR TITLE
Remove usage of "expect"

### PR DESCRIPTION
**Pull request by ihuguet**
This PR remove all usages of "expect" as requested in issue #106, replacing it for a more proper error handling.

The second commit removes an unnecessary error check in `parse_bridge_id`.

### CODE REVIEW

**Comment by ihuguet** [comment]
One thing I have noticed but I didn't change is the usage of `to_ne_bytes` in `parse_bridge_ip`. Using that, the representation will change depending on whether the machine is little endian or big endian.

Is that the expected behaviour? I guess it is because otherwise you can just pass the u16 to `format!`, and you chose not to do it. Just wanted to double check with you.

**Comment by cathay4t** [comment]
> 

I assume you are talking about `parse_bridge_id()`.
In kernel, the sysfs is showing bridge id as:

```c
ssize_t br_show_bridge_id(char *buf, const struct bridge_id *id)
{
	return sprintf(buf, "%.2x%.2x.%.2x%.2x%.2x%.2x%.2x%.2x\n",
	       id->prio[0], id->prio[1],
	       id->addr[0], id->addr[1], id->addr[2],
	       id->addr[3], id->addr[4], id->addr[5]);
}
```

So we cannot show it as u16, and above code also explained why we use `native endian`.

For your PR, please fix the CI failure.

**Comment by ihuguet** [comment]
Thanks for the explanation about bridge ID. CI fixed.

**Review by cathay4t — APPROVED** [review]

**Comment by cathay4t** [comment]
Approved. Please rebase. Thanks!

**Pull request merged**
