### PR TITLE
vxlan, macvtap: upgrade netlink_packet_route

### PR DESCRIPTION
**Pull request by ffmancera**
The new release of netlink_packet_route is needed in order to support
IPoIB on Nispor. Now VXLAN and MAC VLAN support is available at
netlink_packet_route.

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

### CODE REVIEW

**Comment by ffmancera** [comment]
@cathay4t This is needed for #56 but I've found out that the new netlink_packet_route is broken. VXLAN is missing some properties (gpe, gbp..) and IPv4/6 are represented as u32 and u128 which is wrong as they should be Vec<u8> like `netlink_packet_route::rtnl::address::nlas::Nla::Address`.

In addition, MAC VTAP support is not implemented so we cannot re-use MACVTAP/MACVLAN code. I am doing all the fixes and the MAC VTAP support on rust-netlink.

**Comment by ffmancera** [comment]
This depends on https://github.com/little-dude/netlink/issues/123

**Comment by cathay4t** [comment]
@ffmancera Any progress on this?

**Comment by ffmancera** [comment]
@cathay4t Hi, there is an issue with clib and the new tokio version. It seems a memory leak is present. I will contact the tokio community to let them know this, do you agree? Thanks!

**Comment by cathay4t** [comment]
Memory leak is not acceptable for a library. Let's postpone this until memory leak been fixed by our dependents.

**Comment by ffmancera** [comment]
This depends on https://github.com/tokio-rs/tokio/issues/3473, I am preparing a possible workaround (suggestion from @Darksonn)

**Comment by ffmancera** [comment]
@cathay4t ready to review!

**Review by cathay4t — APPROVED** [review]

**Pull request merged**
