### PR TITLE
python: add TUN/TAP support

### PR DESCRIPTION
**Pull request by bengal**

### CODE REVIEW

**Review by cathay4t — CHANGES_REQUESTED** [review]
These properties are optional, please use `get()` instead:
 * owner
 * group
 * num_queues
 * num_disabled_queues

**Comment by bengal** [comment]
> These properties are optional, please use `get()` instead:

Done.

**Comment by cathay4t** [comment]
> > These properties are optional, please use `get()` instead:
> 
> Done.

You have changed all properties into `get()` while only 4 of them are optional. I was expecting the `get()` been used on these 4 options only. Even through they make no difference, but it's good for developer to understand which properties are optional.

**Comment by bengal** [comment]
> > > These properties are optional, please use `get()` instead:
> > 
> > 
> > Done.
> 
> You have changed all properties into `get()` while only 4 of them are optional. I was expecting the `get()` been used on these 4 options only. Even through they make no difference, but it's good for developer to understand which properties are optional.

Yeah, I copied from other interfaces. Fixed now.

**Review by cathay4t — APPROVED** [review]

**Comment by cathay4t** [comment]
Merged. Thanks.

**Pull request merged**
